Vuejs2
bakarasukun/Railstutorial pull request #26
Opened 2020-04-04 07:40 UTC by bakarasukun

2020-04-04 07:58 UTC, MasashiYokota requested changes
簡単にコメントしました。
何度も言っていますが、演算子の前後には絶対にスペースを入れて下さい。

2020-04-04 07:58 UTC, MasashiYokota commented on app/controllers/microposts_controller.rb
> +    pp micropost_params
デバッグコードは消しましょう！

2020-04-04 07:58 UTC, MasashiYokota commented on app/controllers/microposts_controller.rb
> +    #redirect_to request.referrer || root_url
これは、コメントアウトしてよいのかな？

2020-04-04 07:58 UTC, MasashiYokota commented on app/javascript/home/home.vue
> +    if (page=='')page=1;
`==`ではだめです。`===`で書きましょう。
理由を調べて、コメント返信して下さい。

2020-04-04 07:58 UTC, MasashiYokota commented on app/javascript/home/home.vue
> +    console.log(page);
`console.log`とかデバッグコードは消しましょう。

2020-04-04 07:58 UTC, MasashiYokota commented on app/javascript/home/home.vue
> +    } catch(err) {}
エラーハンドリングしないなら、`try ... catch`不要です。

2020-04-04 07:58 UTC, MasashiYokota commented on app/javascript/home/logged_in_home.vue
> +      } catch(err) {};
ここもエラーハンドリングしなしなら、`try ... catch`不要です。

2020-04-04 07:58 UTC, MasashiYokota commented on app/javascript/home/logged_in_home.vue
> +      console.log(val);
`console.log`消しましょう。

2020-04-04 07:58 UTC, MasashiYokota commented on app/javascript/micropost/feed.vue
> +      console.log(val);
デバッグコード消しましょう

2020-04-04 07:58 UTC, MasashiYokota commented on app/javascript/micropost/micropost.vue
> +        } catch(err){};
`try...catch`不要です。

2020-04-04 07:58 UTC, MasashiYokota commented on app/javascript/micropost/micropost.vue
> +      var response = null;
`var`は使ってはいけません。
`let`か`const`を使いましょう。
理由を調べてコメントで返信して下さい。

2020-04-04 07:58 UTC, MasashiYokota commented on app/javascript/micropost/micropost.vue
> +  }
`props`は`computed`や` methods`よりも上に書くと良いです。

2020-04-04 07:58 UTC, MasashiYokota commented on app/javascript/shared/micropost_form.vue
> +      } catch(err){console.log(err)};
`console.log`と`try...catche`

2020-04-04 07:58 UTC, MasashiYokota commented on app/javascript/shared/micropost_form.vue
> +    },
メソッド等の間には空行入れて下さい。

2020-04-04 07:58 UTC, MasashiYokota commented on app/javascript/shared/micropost_form.vue
> +        var size_in_megabytes = this.file.size/1024/1024;
`var` 禁止です。
あと、`1024/1024`はマジックナンバーなので、定数にして下さい。

2020-04-04 07:58 UTC, MasashiYokota commented on app/javascript/shared/micropost_form.vue
> +        if (size_in_megabytes > 5) {
`5`もマジックナンバーなので定数化して下さい。

2020-04-04 07:58 UTC, MasashiYokota commented on app/javascript/shared/user_info.vue
> +      if (count==1){
`==`ダメです。
演算子の前後には、絶対にスペースを入れて下さい。とても読みにくいです。

2020-04-04 07:58 UTC, MasashiYokota commented on app/javascript/home/logged_in_home.vue
> +      var response = null;
varダメです。

2020-04-04 07:58 UTC, MasashiYokota commented on app/javascript/home/home.vue
> +    var response =null;
`var`ダメ。
`=`の前後にspaceお願いします。

2020-04-04 07:58 UTC, MasashiYokota commented on app/javascript/home/home.vue
> +    if (page=='')page=1;
あと、スペースもお願いします。

2020-04-04 08:23 UTC, bakarasukun commented on app/javascript/home/home.vue
> +    if (page=='')page=1;
==だと型変換が行われて予期せぬtrueが発生するため

2020-04-04 08:24 UTC, MasashiYokota commented on app/javascript/home/home.vue
> +    if (page=='')page=1;
正解です 👍 これがないと、意図せぬ挙動となりメンテナンスできなくなるので、気をつけてくださいね！

2020-04-04 08:27 UTC, bakarasukun commented on app/javascript/micropost/micropost.vue
> +      var response = null;
varを用いると宣言前でもその変数が使えてしまうことや、関数全体で使用できることからscopeがわかりづらくなるから

2020-04-04 08:30 UTC, MasashiYokota commented on app/javascript/micropost/micropost.vue
> +      var response = null;
> varを用いると宣言前でもその変数が使えてしまうこと

は少し違いますね。
正確には、`var`が無いとそれはグローバル変数となります。

> 関数全体で使用できることからscopeがわかりづらくなるから

ここは、少しざっくりしすぎですね。例を上げても良いので、もう少し正確に細かく説明お願いします 🙏

2020-04-04 08:33 UTC, bakarasukun commented on app/controllers/microposts_controller.rb
> +    #redirect_to request.referrer || root_url
これをコメントアウトしないとページ遷移させられて、動的なfeedの変化を検証できなかったので消しました

2020-04-04 08:48 UTC, bakarasukun commented on app/javascript/micropost/micropost.vue
> +      var response = null;
var を用いると　例えば
console.log(hoge);
var hoge = 1;
や、
if (){
  var hoge= 10
}
console.log(hoge); 
のようなコードがエラーとならないため、バグが発生し易いからだと思いました

2020-04-04 08:52 UTC, MasashiYokota commented on app/controllers/microposts_controller.rb
> +    #redirect_to request.referrer || root_url
であれば、jsonを返すように修正しましょう。
フロント側だけしか使わない場合、フロント側でリクエストが成功したかどうかを正確に判定する必要があるので。

2020-04-04 08:53 UTC, MasashiYokota commented on app/javascript/micropost/micropost.vue
> +      var response = null;
良いです 👍

2020-04-04 08:58 UTC, MasashiYokota requested changes
コメントしました！

2020-04-04 08:58 UTC, MasashiYokota commented on app/javascript/home/home.vue
> +    response = await axios
const response = await axios
で良いと思います。

2020-04-04 08:58 UTC, MasashiYokota commented on app/javascript/home/logged_in_home.vue
> +      response = await axios
const response = await axios
で良いと思います。

2020-04-04 08:58 UTC, MasashiYokota commented on app/javascript/micropost/micropost.vue
> +          .delete("http://localhost:3000/microposts/"+id);
const response = await axios
ですね。
あと、レスポンスの内容を確認して成功しているかどうかを判定しましょう。

2020-04-04 08:58 UTC, MasashiYokota commented on app/javascript/shared/user_info.vue
> +      }
``` javascript 
if (count === 1){
        return count + ' micropost'
      } else {
        return count + ' microposts'
      }
}

2020-04-04 08:58 UTC, MasashiYokota commented on app/javascript/home/home.vue
> +    let page = query.replace("?page=", "");
const page = location.search.replace("?page=", "");
で良いと思います。

2020-04-04 09:48 UTC, MasashiYokota commented on app/javascript/home/home.vue
> +  <not_logged_in_home v-else></not_logged_in_home>
`not_logged_in_home`を消して、<template v-if =...>でlogged_in_homeを囲みましょう。

2020-04-04 10:17 UTC, MasashiYokota commented on app/controllers/microposts_controller.rb
> +      #redirect_to root_url
json返して下さい

2020-04-04 10:18 UTC, MasashiYokota commented on app/controllers/microposts_controller.rb
> +    #redirect_to request.referrer || root_url
json返して下さい

2020-04-04 10:19 UTC, MasashiYokota commented on app/controllers/static_pages_controller.rb
> +  def api
`api`って全部APIなので、適切な名前付けをして下さい。
あと、controllerも`static_page`にそのAPIを生やすのは適切ですか？
新しく生やす先も考え直して下さい。

2020-04-10 10:53 UTC, MasashiYokota commented on app/javascript/micropost/micropost.vue
> +    async del_confirm(id){
`async del_confirm(id){`にスペース入れて下さい。（何回も言っています。）

2020-04-10 10:53 UTC, MasashiYokota commented on app/javascript/micropost/micropost.vue
> +        alert(response.data.msg);
`.delete`の前の改行不要。
tryの中のインデントおかしいです

2020-04-10 10:54 UTC, MasashiYokota commented on app/javascript/micropost/micropost.vue
> +          .delete("http://localhost:3000/microposts/"+id);
テンプレート使って下さい。

2020-04-10 10:54 UTC, MasashiYokota commented on app/javascript/micropost/micropost.vue
> +        this.$emit('chagneFeed',1);
スペース

2020-04-10 10:56 UTC, MasashiYokota commented on app/javascript/micropost/feed.vue
> +        @changeFeed='ChildChangeFeed'
`change-feed `

2020-04-10 10:56 UTC, MasashiYokota commented on app/javascript/home/not_logged_in_home.vue
> +      v-on:click="window.location.href =`http://localhost:3000/signup`">
`@click`

2020-04-12 04:31 UTC, MasashiYokota commented on app/controllers/microposts_controller.rb
> +      #redirect_to root_url
不要なコードは削除して下さい

2020-04-12 04:31 UTC, MasashiYokota commented on app/controllers/microposts_controller.rb
> +    #redirect_to request.referrer || root_url
ここも

2020-04-12 04:34 UTC, MasashiYokota commented on app/javascript/shared/user_info.vue
> +      if(count === 1) {
`if (count === 1) {`

2020-04-12 04:36 UTC, MasashiYokota commented on app/controllers/api_controller.rb
> +end
こういうAPIの作り方はダメです。
例えば、`feed_api`はちゃんと`FeedsController`を作って`index`アクションに上記のロジックを入れて下さい。(user_apiも同様にUserControllerに生やして下さい。)

2020-04-12 05:30 UTC, MasashiYokota commented
以下の質問の回答をコメントで返信して下さい。

1. `v-on`と`v-bind`の違いを教えて下さい。
1. `methods`と`computed`の違いを教えて下さい。
2. vue.jsでデータがリアクティブにならない場合を教えて下さい。また、その対処法を教えて下さい。
3. `v-for`で`key`を指定しないといけない理由を教えて下さい。

2020-04-12 05:53 UTC, bakarasukun commented
1 v-onはイベントに対してメソッドなどを実行するように関連づけるもので、v-bindはidなどの属性やデータを関連づけるものです。
2 methodsは呼ばれると内部のコードを実行して結果を返しますが、computedはデータが変更された時のみコードを実行し、更新されていない時はキャッシュを用いて返します。
3 Vue インスタンスのdataオブジェクトで宣言されていないインスタンス　最初に適当な値で初期化したインスタンスをdataで宣言することで対処できます。
4 vueの内部で各要素を一意に指定することによって描画が変化する際にその要素を用いることで描画のコストを減らしているからです。

2020-04-12 05:56 UTC, MasashiYokota commented
> vueの内部で各要素を一意に指定することによって描画が変化する際にその要素を用いることで描画のコストを減らしているからです。

もう少し深く説明してみましょう。具体的には`v-for`に`key`があるときとないときで明確に描画のアルゴリズムが変わりますので、その点を交えて説明して下さい。

2020-04-12 06:16 UTC, bakarasukun commented
v-forでkeyを付けない場合、関連づけられた配列が変化すると現在作られたdomを再利用し、各々の要素を上書きすることによって描画を変更しますが、keyを指定すると、一意に決められたkeyでネストされたDOMを用いて描画を変更します。

2020-04-12 06:17 UTC, MasashiYokota commented
LGTM 👍 
マージしてOKです

2020-04-12 06:17 UTC, merged